server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-customer
          uri: lb://service-customer
          predicates:
            - Path=/api/customers/**
        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/api/products/**
        - id: service-shopping
          uri: lb://service-shopping
          predicates:
            - Path=/api/invoices/**